language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
branches:
  only:
  - master
  - "/^iterator-reflection-[0-9]+\\.[0-9]+\\.[0-9]+/"
after_success:
- mvn clean test jacoco:report coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings settings.xml
